### ISSUE TITLE
Will you consider open source your project ?

### ISSUE THREAD

**Issue by oxarbitrage** [aronerben/lean-rsa#1]
Hey, i was looking for crypto schemes formalization attempts in lean and found your project which is pretty good.

I have an idea to include it in https://github.com/JoeyLupo/cryptolib which is i think the most complete attempt up to date.

Will you consider adding a permissive open source license to your project so people can contribute to it ?

I am asking the same question to the cryptolib owner at https://github.com/JoeyLupo/cryptolib/issues/1

I have a pull request that updates the cryptolib mathlib to the version used in rsa-lean and then another one that adds your `rsa.lean` file into the project:

https://github.com/oxarbitrage/cryptolib/pull/1
https://github.com/oxarbitrage/cryptolib/pull/2

Another option could be to include `lean-rsa` as a submodule of `cryprolib` but this is a bit trickier.

Let me know what do you think. Thanks for the great work done.

**Comment by aronerben** [comment]
Hello @oxarbitrage !

Thanks for your kind message and sorry for the delayed response. I've added an MIT license to the project. I hope this is permissive enough for your purposes :)

Let me know if I can be of any further assistance!

**Comment by aronerben** [comment]
A quick note, which I briefly mentioned in the `README` already: I often made use of just plain `simp` in the proof, so if mathlib versions are upgraded in the future, this might cause breakage. The way to fix it here would be to just do `simp?` or `squeeze_simp` and replace `simp?`/`squeeze_simp` with the output.

**Comment by oxarbitrage** [comment]
Hi @aronerben , thank you for the response. 

> Thanks for your kind message and sorry for the delayed response. I've added an MIT license to the project. I hope this is permissive enough for your purposes :)

Yea, that is more than enough for me, very appreciated.

> A quick note, which I briefly mentioned in the README already: I often made use of just plain simp in the proof, so if mathlib versions are upgraded in the future, this might cause breakage. The way to fix it here would be to just do simp? or squeeze_simp and replace simp?/squeeze_simp with the output.

This is a good advice, i will try to upgrade to one of the latest mathlib versions using that and see if i can make it. 

Thanks again for everything.

**Comment by aronerben** [comment]
@oxarbitrage Cheers! 

I forgot to add [this quick link](https://leanprover-community.github.io/extras/simp.html#non-terminal-simps) which explains the whole deal with using "non-terminal" `simp`s in further detail. I was not aware this was an anti-pattern when I wrote this proof :)
